spring:
  main:
    web-application-type: none
  application:
    name: 13-guardrails
  config:
    import:
      - "optional:file:../config/langchain4j-common.yml"
      - "optional:file:./config/langchain4j-common.yml"
