spring:
  main:
    web-application-type: none
  application:
    name: 07-structured-outputs
  config:
    import:
      - "optional:file:../config/langchain4j-common.yml"
      - "optional:file:./config/langchain4j-common.yml"
      - "optional:file:langchain4j-learning/config/langchain4j-common.yml"   # 在仓库(ai-learning)根目录 / IDE 默认工作目录运行时
